# -*- coding: utf-8 -*-
"""webscraping_sigef.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17d-TzpF9zBrrEAZvjHEWJs5btuPQMKrU
"""

from urllib.request import urlopen

# o trecho abaixo é o q faz o código aceitar o site com certificado não verificado
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

url = "xxxxxxxxxxxxxxxx"
resposta = urlopen(url)
html = resposta.read().decode("utf-8")

partes = html.split("CPF/CNPJ</th>\n        </tr>\n        </thead>\n        <tbody>\n\n        \n\n            <tr>\n                <td>")

len(partes)

for parte in partes:
  subparte = parte.split("</td>\n")
  nome = subparte[0]
  documento = subparte[1]

print(nome)
print(documento)